/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * coba.java
 *
 * Created on May 18, 2015, 6:49:54 PM
 */

package pbo.form;

import java.awt.Color;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import pbo.util.ConectionDB;
import pbo.util.FungsiDatabase;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
//import sun.invoke.empty.Empty;

/**
 *
 * @author Dell
 */
public class coba extends javax.swing.JFrame {
Statement stmt;
ResultSet rs;
Connection con;
    /** Creates new form coba */
    public coba() {
        initComponents();
        openConnection();

      /*  final Timer timer = new Timer(1000, new ActionListener() {
	public void actionPerformed(ActionEvent e) {

                String strJam = new SimpleDateFormat("HH:mm:ss").format(new Date());
		lbl_jam.setText(strJam);
                
               try{

                     stmt = con.createStatement();
                     rs = stmt.executeQuery("SELECT ruang FROM tbl_coba WHERE ruang = 'r401' AND '"+lbl_jam.getText()+"' BETWEEN masuk AND keluar");

                  try{
                      System.out.println(rs.getString(1));
                  labelKetos.setText("isi");
                  
                  }catch(Exception sc)
                  {
                   labelKetos.setText("kosong");
                  }

                    }catch(SQLException ex)
                             {

                                   ex.printStackTrace();
                             }
               try{

                     stmt = con.createStatement();
                     rs = stmt.executeQuery("SELECT ruang FROM tbl_coba WHERE ruang = 'r402' AND '"+lbl_jam.getText()+"' BETWEEN masuk AND keluar");

                  try{
                      System.out.println(rs.getString(1));
                  labelKetos1.setText("isi");

                  }catch(Exception sc)
                  {
                   labelKetos1.setText("kosong");
                  }

                    }catch(SQLException ex)
                             {

                                   ex.printStackTrace();
                             }
               
             try{

                     stmt = con.createStatement();
                     rs = stmt.executeQuery("SELECT ruang FROM tbl_coba WHERE ruang = 'r403' AND '"+lbl_jam.getText()+"' BETWEEN masuk AND keluar");

                  try{
                      String id= rs.getString("ruang");
                  labelKetos2.setText("isi");

                  }catch(Exception sc)
                  {
                  // labelKetos2.setText("kosong");
                      sc.printStackTrace();
                  }

                    }catch(SQLException ex)
                             {

                                   ex.printStackTrace();
                             }
            }
} );
timer.start();

Timer timer2 = new Timer(1000, new ActionListener() {
	public void actionPerformed(ActionEvent e) {

                String strJam = new SimpleDateFormat("hh:mm:ss").format(new Date());
		lbl_jam1.setText(strJam);

                if (lbl_jam1.getText().equals("07:10:00"))
                {
                    lbl_banding.setText("07:10:30");
                }
                else
                {
                lbl_banding.setText("beda");
                }


	}
} );
timer2.start();

*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_jam = new javax.swing.JLabel();
        lbl_banding = new javax.swing.JLabel();
        lbl_banding1 = new javax.swing.JLabel();
        lbl_jam1 = new javax.swing.JLabel();
        labelKetos = new javax.swing.JLabel();
        labelKetos1 = new javax.swing.JLabel();
        labelKetos2 = new javax.swing.JLabel();
        lbl_cek = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_jam.setText("jLabel1");

        lbl_banding.setText("07:02:00");

        lbl_banding1.setText("07:04:00");

        lbl_jam1.setText("jLabel1");

        labelKetos.setBackground(new java.awt.Color(255, 255, 255));
        labelKetos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelKetos.setOpaque(true);
        labelKetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKetosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelKetosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelKetosMouseExited(evt);
            }
        });

        labelKetos1.setBackground(new java.awt.Color(255, 255, 255));
        labelKetos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelKetos1.setOpaque(true);
        labelKetos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKetos1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelKetos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelKetos1MouseExited(evt);
            }
        });

        labelKetos2.setBackground(new java.awt.Color(255, 255, 255));
        labelKetos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelKetos2.setOpaque(true);
        labelKetos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKetos2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelKetos2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelKetos2MouseExited(evt);
            }
        });

        lbl_cek.setText("16:00:00");

        jLabel1.setText("12:00:00");

        jLabel2.setText("13:00:00");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\gifcoba.gif")); // NOI18N
        jLabel3.setText("jLabel3");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(lbl_jam))
                    .addComponent(labelKetos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelKetos1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(labelKetos2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(lbl_jam1)
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(lbl_banding, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cek, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_banding1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_jam1)
                            .addComponent(lbl_banding, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_banding1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_cek, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbl_jam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelKetos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKetos2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKetos1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void openConnection()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            this.con = DriverManager.getConnection("jdbc:mysql://" +
                    "localhost:3306/db_pbo","root","");
            System.out.println("koneksi berhasil");
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch(SQLException sqle){
            sqle.printStackTrace();

        }


    }
    private void labelKetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKetosMouseClicked
        // TODO add your handling code here:

}//GEN-LAST:event_labelKetosMouseClicked

    private void labelKetosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKetosMouseEntered
    cek();
}//GEN-LAST:event_labelKetosMouseEntered
public void cek ()
{
    try{
    stmt = con.createStatement();
    rs = stmt.executeQuery("SELECT ruangan_kode FROM tbl_jadwal WHERE ruangan_kode = 'r409' AND hari='jumat' and '16:00:00' BETWEEN jam_masuk AND jam_keluar");

    rs.first();
    String nama = rs.getString("ruangan_kode");
    System.out.print(nama);

    if (nama.equals(""))
    {
        System.out.println("kosong");
    }
    else
    {
    System.out.println("isi");
    }

    }
    catch(SQLException se)
                {
                     System.out.println("kosong");

                }
}
    private void labelKetosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKetosMouseExited
         labelKetos.setText("cek");
}//GEN-LAST:event_labelKetosMouseExited

    private void labelKetos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKetos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelKetos1MouseClicked

    private void labelKetos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKetos1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelKetos1MouseEntered

    private void labelKetos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKetos1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelKetos1MouseExited

    private void labelKetos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKetos2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelKetos2MouseClicked

    private void labelKetos2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKetos2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelKetos2MouseEntered

    private void labelKetos2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKetos2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelKetos2MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

     String waktu1,waktu2;
     waktu1= jLabel1.getText();
     waktu2= jLabel2.getText();

     String waktu [] = waktu1.split(":");
     String jam = waktu[0];
     String menit = waktu[1];
     String detik = waktu[2];

     String waktuu [] = waktu2.split(":");
     String jam1 = waktuu[0];
     String menit1 = waktuu[1];
     String detik1 = waktuu[2];

     int detik11 = Integer.parseInt(detik);
     int detik111 = Integer.parseInt(detik1);

     int menit11 = Integer.parseInt(menit);
     int menit111 = Integer.parseInt(menit1);

     int jam11 = Integer.parseInt(jam);
     int jam111 = Integer.parseInt(jam1);

     int de,me,ja,hasil1,de1,me1,ja1,hasil2,hasil;

    de=detik11;
     me = menit11*60;
     ja = jam11*3600;

     hasil1 = de+me+ja;

     de1=detik111;
     me1 = menit111*60;
     ja1 = jam111*3600;

     hasil2 = de1+me1+ja1;

        System.out.println(""+jam11);
        System.out.println(""+jam111);
        System.out.println(""+hasil1);
        System.out.println(""+hasil2);
     if (hasil1 >=  hasil2)
     {
        System.out.print("masuk");
     }else
     {
        System.out.print("pulang");

     }
     





      


       













    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelKetos;
    private javax.swing.JLabel labelKetos1;
    private javax.swing.JLabel labelKetos2;
    private javax.swing.JLabel lbl_banding;
    private javax.swing.JLabel lbl_banding1;
    private javax.swing.JLabel lbl_cek;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_jam1;
    // End of variables declaration//GEN-END:variables

}
