/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmMenuRuang.java
 *
 * Created on May 9, 2015, 3:36:34 PM
 */

package pbo.form;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import pbo.util.ConectionDB;
import pbo.util.FungsiLayout;
/**
 *
 * @author Dell
 */
public class FrmMenuUtama extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
    /** Creates new form FrmMenuRuang */
    public FrmMenuUtama() {
        initComponents();

        openConnection();
        Timer timer = new Timer(1000, new ActionListener() {
	public void actionPerformed(ActionEvent e) {
		String strhari = new SimpleDateFormat("EEEE").format(new Date());
		lbl_hari.setText(strhari);
                String strJam = new SimpleDateFormat("H:mm:ss").format(new Date());
		lbl_jam.setText(strJam);
                 String strtgl = new SimpleDateFormat("dd MMMMM yyyy").format(new Date());
		lbl_tanggal.setText(strtgl);

                if (lbl_hari.getText().equals("Sunday"))
        {
            lbl_hari.setText("Minggu");
        }else if (lbl_hari.getText().equals("Monday"))
        {
            lbl_hari.setText("Senin");
        }else if (lbl_hari.getText().equals("Tuesday"))
        {
            lbl_hari.setText("Selasa");
        }else if (lbl_hari.getText().equals("Wednesday"))
        {
            lbl_hari.setText("Rabu");
        }else if (lbl_hari.getText().equals("Thursday"))
        {
            lbl_hari.setText("Kamis");
        }else if (lbl_hari.getText().equals("Friday"))
        {
            lbl_hari.setText("Jumat");
        }else if (lbl_hari.getText().equals("Saturday"))
        {
            lbl_hari.setText("Sabtu");
        }
	}
} );
timer.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbl_ruang = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_ruangan1 = new javax.swing.JLabel();
        lbl_ruangan2 = new javax.swing.JLabel();
        lbl_ruangan3 = new javax.swing.JLabel();
        lbl_ruangan4 = new javax.swing.JLabel();
        lbl_hari = new javax.swing.JLabel();
        lbl_ruangan5 = new javax.swing.JLabel();
        lbl_jam = new javax.swing.JLabel();
        lbl_tanggal = new javax.swing.JLabel();
        lbl_ruangan6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Pengelolaan Absensi Mahasiswa | Menu Utama");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbl_ruang.setText("jLabel3");
        lbl_ruang.setBounds(0, 0, 34, 14);
        jLayeredPane1.add(lbl_ruang, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/botKeluar.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(2935, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel2.setBounds(0, 680, 3039, 138);
        jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_ruangan1.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/menu 1.png"))); // NOI18N
        lbl_ruangan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan1.setOpaque(true);
        lbl_ruangan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan1MouseExited(evt);
            }
        });
        lbl_ruangan1.setBounds(20, 110, 432, 129);
        jLayeredPane1.add(lbl_ruangan1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_ruangan2.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan2.setFont(new java.awt.Font("Century Gothic", 0, 48));
        lbl_ruangan2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ruangan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/menu 3.png"))); // NOI18N
        lbl_ruangan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan2.setOpaque(true);
        lbl_ruangan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan2MouseExited(evt);
            }
        });
        lbl_ruangan2.setBounds(20, 390, 432, 129);
        jLayeredPane1.add(lbl_ruangan2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_ruangan3.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/menu 2.png"))); // NOI18N
        lbl_ruangan3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan3.setOpaque(true);
        lbl_ruangan3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan3MouseExited(evt);
            }
        });
        lbl_ruangan3.setBounds(20, 250, 432, 129);
        jLayeredPane1.add(lbl_ruangan3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_ruangan4.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/menu 4.png"))); // NOI18N
        lbl_ruangan4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan4.setOpaque(true);
        lbl_ruangan4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan4MouseExited(evt);
            }
        });
        lbl_ruangan4.setBounds(20, 530, 432, 129);
        jLayeredPane1.add(lbl_ruangan4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_hari.setFont(new java.awt.Font("Century Gothic", 0, 18));
        lbl_hari.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hari.setText("Selasa");
        lbl_hari.setBounds(40, 80, 90, 23);
        jLayeredPane1.add(lbl_hari, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_ruangan5.setBackground(new java.awt.Color(0, 0, 0));
        lbl_ruangan5.setFont(new java.awt.Font("Century Gothic", 0, 48));
        lbl_ruangan5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ruangan5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/logo.png"))); // NOI18N
        lbl_ruangan5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan5.setOpaque(true);
        lbl_ruangan5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan5MouseExited(evt);
            }
        });
        lbl_ruangan5.setBounds(1210, 20, 120, 100);
        jLayeredPane1.add(lbl_ruangan5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_jam.setFont(new java.awt.Font("Century Gothic", 0, 48));
        lbl_jam.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jam.setText("00:00:00");
        lbl_jam.setBounds(40, 20, 188, 60);
        jLayeredPane1.add(lbl_jam, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_tanggal.setFont(new java.awt.Font("Century Gothic", 0, 18));
        lbl_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tanggal.setText("Selasa");
        lbl_tanggal.setBounds(110, 80, 160, 23);
        jLayeredPane1.add(lbl_tanggal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_ruangan6.setBackground(new java.awt.Color(0, 0, 0));
        lbl_ruangan6.setFont(new java.awt.Font("Century Gothic", 0, 48));
        lbl_ruangan6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ruangan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/sipam.png"))); // NOI18N
        lbl_ruangan6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan6.setOpaque(true);
        lbl_ruangan6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan6MouseExited(evt);
            }
        });
        lbl_ruangan6.setBounds(550, 60, 640, 920);
        jLayeredPane1.add(lbl_ruangan6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2651, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void openConnection()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            this.con = DriverManager.getConnection("jdbc:mysql://" +
                    "localhost:3306/db_pbo","root","");
            System.out.println("koneksi berhasil");
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch(SQLException sqle){
            sqle.printStackTrace();

        }
}
    private void lbl_ruangan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan1MouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        FrmMenuRuang fm = new FrmMenuRuang();
        FungsiLayout.setToCenter(fm);
        FungsiLayout.setMaximize(fm);
        fm.setVisible(true);
        dispose();
}//GEN-LAST:event_lbl_ruangan1MouseClicked

    private void lbl_ruangan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan1MouseEntered
    lbl_ruangan1.setBackground(Color.RED);
}//GEN-LAST:event_lbl_ruangan1MouseEntered

    private void lbl_ruangan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan1MouseExited
     lbl_ruangan1.setBackground(new Color(0,204,255));
}//GEN-LAST:event_lbl_ruangan1MouseExited

    private void lbl_ruangan2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan2MouseClicked
        // TODO add your handling code here:
        FrmJadwalKuliah fj = new FrmJadwalKuliah();
        FungsiLayout.setToCenter(fj);
        FungsiLayout.setMaximize(fj);
        fj.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_ruangan2MouseClicked

    private void lbl_ruangan2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan2MouseEntered
        // TODO add your handling code here:
        lbl_ruangan2.setBackground(Color.RED);
    }//GEN-LAST:event_lbl_ruangan2MouseEntered

    private void lbl_ruangan2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan2MouseExited
        // TODO add your handling code here:
         lbl_ruangan2.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan2MouseExited

    private void lbl_ruangan3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan3MouseClicked
        // TODO add your handling code here:
        FrmKelas fk = new FrmKelas();
        FungsiLayout.setToCenter(fk);
        FungsiLayout.setMaximize(fk);
        fk.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_ruangan3MouseClicked

    private void lbl_ruangan3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan3MouseEntered
        // TODO add your handling code here:
        lbl_ruangan3.setBackground(Color.RED);

    }//GEN-LAST:event_lbl_ruangan3MouseEntered

    private void lbl_ruangan3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan3MouseExited
        // TODO add your handling code here:
        lbl_ruangan3.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan3MouseExited

    private void lbl_ruangan4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan4MouseClicked
        // TODO add your handling code here:
        FrmAbout fa = new FrmAbout();
        FungsiLayout.setToCenter(fa);
        FungsiLayout.setMaximize(fa);
        fa.setVisible(true);
      
    }//GEN-LAST:event_lbl_ruangan4MouseClicked

    private void lbl_ruangan4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan4MouseEntered
        // TODO add your handling code here:
        lbl_ruangan4.setBackground(Color.RED);

    }//GEN-LAST:event_lbl_ruangan4MouseEntered

    private void lbl_ruangan4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan4MouseExited
        // TODO add your handling code here:
          lbl_ruangan4.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan4MouseExited
 public ResultSet fQuery(String SQL_String) {
        ResultSet record;
        System.out.println(SQL_String);
        try {
            Statement st = con.createStatement();
            record =  st.executeQuery(SQL_String);

            return record;
        } catch (Exception ex) {
            return null;
        }
    }
    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel2KeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lbl_ruangan5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ruangan5MouseClicked

    private void lbl_ruangan5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ruangan5MouseEntered

    private void lbl_ruangan5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ruangan5MouseExited

    private void lbl_ruangan6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ruangan6MouseClicked

    private void lbl_ruangan6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ruangan6MouseEntered

    private void lbl_ruangan6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ruangan6MouseExited

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_hari;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_ruang;
    private javax.swing.JLabel lbl_ruangan1;
    private javax.swing.JLabel lbl_ruangan2;
    private javax.swing.JLabel lbl_ruangan3;
    private javax.swing.JLabel lbl_ruangan4;
    private javax.swing.JLabel lbl_ruangan5;
    private javax.swing.JLabel lbl_ruangan6;
    private javax.swing.JLabel lbl_tanggal;
    // End of variables declaration//GEN-END:variables

}
