/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmMenuRuang.java
 *
 * Created on May 9, 2015, 3:36:34 PM
 */

package pbo.form;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javazoom.jl.player.Player;
import pbo.util.ConectionDB;
import pbo.util.FungsiLayout;
/**
 *
 * @author Dell
 */
public class FrmMenuRuang extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
    /** Creates new form FrmMenuRuang */
    public FrmMenuRuang() {
        initComponents();
        lbl_pangilRuang.setVisible(false);
        lbl_ruang.setVisible(false);
        openConnection();
        Timer timer = new Timer(1000, new ActionListener() {
	public void actionPerformed(ActionEvent e) {
		String strhari = new SimpleDateFormat("EEEE").format(new Date());
	//	lbl_hari.setText(strhari);
                String strJam = new SimpleDateFormat("H:mm:ss").format(new Date());
	//	lbl_jam.setText(strJam);
                 String strtgl = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
	//	lbl_tanggal.setText(strtgl);

                if (lbl_hari.getText().equals("Sunday"))
        {
            lbl_hari.setText("Minggu");
        }else if (lbl_hari.getText().equals("Monday"))
        {
            lbl_hari.setText("Senin");
        }else if (lbl_hari.getText().equals("Tuesday"))
        {
            lbl_hari.setText("Selasa");
        }else if (lbl_hari.getText().equals("Wednesday"))
        {
            lbl_hari.setText("Rabu");
        }else if (lbl_hari.getText().equals("Thursday"))
        {
            lbl_hari.setText("Kamis");
        }else if (lbl_hari.getText().equals("Friday"))
        {
            lbl_hari.setText("Jumat");
        }else if (lbl_hari.getText().equals("Saturday"))
        {
            lbl_hari.setText("Sabtu");
        }
	}
} );
timer.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_ruangan1 = new javax.swing.JLabel();
        lbl_ruangan2 = new javax.swing.JLabel();
        lbl_ruangan3 = new javax.swing.JLabel();
        lbl_ruangan4 = new javax.swing.JLabel();
        lbl_ruangan5 = new javax.swing.JLabel();
        lbl_ruangan6 = new javax.swing.JLabel();
        lbl_ruangan7 = new javax.swing.JLabel();
        lbl_ruangan8 = new javax.swing.JLabel();
        lbl_ruangan9 = new javax.swing.JLabel();
        lbl_ruangan10 = new javax.swing.JLabel();
        lbl_ruangan11 = new javax.swing.JLabel();
        lbl_ruangan12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_jam = new javax.swing.JLabel();
        lbl_hari = new javax.swing.JLabel();
        lbl_tanggal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_ruang = new javax.swing.JLabel();
        lbl_pangilRuang = new javax.swing.JLabel();

        setTitle("Sistem Informasi Pengelolaan Absensi Mahasiswa");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbl_ruangan1.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/1.png"))); // NOI18N
        lbl_ruangan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan1.setOpaque(true);
        lbl_ruangan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan1MouseExited(evt);
            }
        });

        lbl_ruangan2.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan2.setFont(new java.awt.Font("Century Gothic", 0, 48));
        lbl_ruangan2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ruangan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/2.png"))); // NOI18N
        lbl_ruangan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan2.setOpaque(true);
        lbl_ruangan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan2MouseExited(evt);
            }
        });

        lbl_ruangan3.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/3.png"))); // NOI18N
        lbl_ruangan3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan3.setOpaque(true);
        lbl_ruangan3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan3MouseExited(evt);
            }
        });

        lbl_ruangan4.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/4.png"))); // NOI18N
        lbl_ruangan4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan4.setOpaque(true);
        lbl_ruangan4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan4MouseExited(evt);
            }
        });

        lbl_ruangan5.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/5.png"))); // NOI18N
        lbl_ruangan5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan5.setOpaque(true);
        lbl_ruangan5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan5MouseExited(evt);
            }
        });

        lbl_ruangan6.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/6.png"))); // NOI18N
        lbl_ruangan6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan6.setOpaque(true);
        lbl_ruangan6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan6MouseExited(evt);
            }
        });

        lbl_ruangan7.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/7.png"))); // NOI18N
        lbl_ruangan7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan7.setOpaque(true);
        lbl_ruangan7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan7MouseExited(evt);
            }
        });

        lbl_ruangan8.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/8.png"))); // NOI18N
        lbl_ruangan8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan8.setOpaque(true);
        lbl_ruangan8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan8MouseExited(evt);
            }
        });

        lbl_ruangan9.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/9.png"))); // NOI18N
        lbl_ruangan9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan9.setOpaque(true);
        lbl_ruangan9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan9MouseExited(evt);
            }
        });

        lbl_ruangan10.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/10_1.png"))); // NOI18N
        lbl_ruangan10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan10.setOpaque(true);
        lbl_ruangan10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan10MouseExited(evt);
            }
        });

        lbl_ruangan11.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/11.png"))); // NOI18N
        lbl_ruangan11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan11.setOpaque(true);
        lbl_ruangan11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan11MouseExited(evt);
            }
        });

        lbl_ruangan12.setBackground(new java.awt.Color(0, 204, 255));
        lbl_ruangan12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/10.png"))); // NOI18N
        lbl_ruangan12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ruangan12.setOpaque(true);
        lbl_ruangan12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ruangan12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ruangan12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ruangan12MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 48));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/Judulb.png"))); // NOI18N

        lbl_jam.setFont(new java.awt.Font("Century Gothic", 0, 48));
        lbl_jam.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jam.setText("12:40:00");

        lbl_hari.setFont(new java.awt.Font("Century Gothic", 0, 18));
        lbl_hari.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hari.setText("Jumat");

        lbl_tanggal.setFont(new java.awt.Font("Century Gothic", 0, 18));
        lbl_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tanggal.setText("04-05-2015");

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/gambar/botKeluar.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1283, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        lbl_ruang.setText("jLabel3");

        lbl_pangilRuang.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbl_ruang)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_ruangan9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_ruangan12, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_ruangan11, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbl_ruangan5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lbl_ruangan6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lbl_ruangan7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbl_ruangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_ruangan2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lbl_ruangan3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ruangan10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_ruangan8, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_ruangan4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 576, Short.MAX_VALUE)
                                .addComponent(lbl_jam))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_pangilRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(lbl_hari)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_tanggal)))
                .addGap(151, 151, 151))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_jam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_tanggal)
                                    .addComponent(lbl_hari)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_pangilRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_ruangan4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_ruangan8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_ruangan10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ruangan3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ruangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ruangan2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ruangan6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ruangan5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ruangan7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ruangan12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ruangan9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ruangan11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(lbl_ruang)))
                .addGap(77, 77, 77)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void openConnection()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            this.con = DriverManager.getConnection("jdbc:mysql://" +
                    "localhost:3306/db_pbo","root","");
            System.out.println("koneksi berhasil");
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch(SQLException sqle){
            sqle.printStackTrace();

        }
}
    private void lbl_ruangan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan1MouseClicked
      
        lbl_ruang.setText("R401");
        panggilRuang();

        
}//GEN-LAST:event_lbl_ruangan1MouseClicked

    private void lbl_ruangan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan1MouseEntered
    lbl_ruangan1.setBackground(Color.RED);
     play("key.mp3");
}//GEN-LAST:event_lbl_ruangan1MouseEntered

    private void lbl_ruangan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan1MouseExited
     lbl_ruangan1.setBackground(new Color(0,204,255));
}//GEN-LAST:event_lbl_ruangan1MouseExited

    private void lbl_ruangan2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan2MouseClicked
        // TODO add your handling code here:
        lbl_ruang.setText("R402");
        panggilRuang();
        
    }//GEN-LAST:event_lbl_ruangan2MouseClicked

    private void lbl_ruangan2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan2MouseEntered
        // TODO add your handling code here:
        lbl_ruangan2.setBackground(Color.RED);
         play("key.mp3");
    }//GEN-LAST:event_lbl_ruangan2MouseEntered

    private void lbl_ruangan2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan2MouseExited
        // TODO add your handling code here:
         lbl_ruangan2.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan2MouseExited

    private void lbl_ruangan3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan3MouseClicked
        // TODO add your handling code here:
        lbl_ruang.setText("R403");
        panggilRuang();
    }//GEN-LAST:event_lbl_ruangan3MouseClicked

    private void lbl_ruangan3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan3MouseEntered
        // TODO add your handling code here:
        lbl_ruangan3.setBackground(Color.RED);
         play("key.mp3");

    }//GEN-LAST:event_lbl_ruangan3MouseEntered

    private void lbl_ruangan3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan3MouseExited
        // TODO add your handling code here:
        lbl_ruangan3.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan3MouseExited

    private void lbl_ruangan4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan4MouseClicked
        // TODO add your handling code here:
        lbl_ruang.setText("R404");
        panggilRuang();

    }//GEN-LAST:event_lbl_ruangan4MouseClicked

    private void lbl_ruangan4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan4MouseEntered
        // TODO add your handling code here:
        lbl_ruangan4.setBackground(Color.RED);
         play("key.mp3");

    }//GEN-LAST:event_lbl_ruangan4MouseEntered

    private void lbl_ruangan4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan4MouseExited
        // TODO add your handling code here:
          lbl_ruangan4.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan4MouseExited

    private void lbl_ruangan5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan5MouseClicked
        // TODO add your handling code here:
        lbl_ruang.setText("R405");
        panggilRuang();
    }//GEN-LAST:event_lbl_ruangan5MouseClicked

    private void lbl_ruangan5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan5MouseEntered
        // TODO add your handling code here:
         lbl_ruangan5.setBackground(Color.RED);
          play("key.mp3");
    }//GEN-LAST:event_lbl_ruangan5MouseEntered

    private void lbl_ruangan5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan5MouseExited
        // TODO add your handling code here:
         lbl_ruangan5.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan5MouseExited

    private void lbl_ruangan6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan6MouseClicked
        // TODO add your handling code here:
        lbl_ruang.setText("R406");
        panggilRuang();
    }//GEN-LAST:event_lbl_ruangan6MouseClicked

    private void lbl_ruangan6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan6MouseEntered
        // TODO add your handling code here:
         lbl_ruangan6.setBackground(Color.RED);
          play("key.mp3");
    }//GEN-LAST:event_lbl_ruangan6MouseEntered

    private void lbl_ruangan6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan6MouseExited
        // TODO add your handling code here:
         lbl_ruangan6.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan6MouseExited
 public ResultSet fQuery(String SQL_String) {
        ResultSet record;
        System.out.println(SQL_String);
        try {
            Statement st = con.createStatement();
            record =  st.executeQuery(SQL_String);

            return record;
        } catch (Exception ex) {
            return null;
        }
    }
    private void lbl_ruangan7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan7MouseClicked
        // TODO add your handling code here:
        lbl_ruang.setText("R407");
        panggilRuang();
    }//GEN-LAST:event_lbl_ruangan7MouseClicked

    private void lbl_ruangan7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan7MouseEntered
        // TODO add your handling code here:
         lbl_ruangan7.setBackground(Color.RED);
          play("key.mp3");
    }//GEN-LAST:event_lbl_ruangan7MouseEntered

    private void lbl_ruangan7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan7MouseExited
        // TODO add your handling code here:
         lbl_ruangan7.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan7MouseExited

    private void lbl_ruangan8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan8MouseClicked
        // TODO add your handling code here:
        lbl_ruang.setText("R409");
        panggilRuang();
    }//GEN-LAST:event_lbl_ruangan8MouseClicked

    private void lbl_ruangan8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan8MouseEntered
        // TODO add your handling code here:
        lbl_ruangan8.setBackground(Color.RED);
         play("key.mp3");
    }//GEN-LAST:event_lbl_ruangan8MouseEntered

    private void lbl_ruangan8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan8MouseExited
        // TODO add your handling code here:
         lbl_ruangan8.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan8MouseExited

    private void lbl_ruangan9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan9MouseClicked
        // TODO add your handling code here:
        lbl_ruang.setText("R410");
        panggilRuang();
    }//GEN-LAST:event_lbl_ruangan9MouseClicked

    private void lbl_ruangan9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan9MouseEntered
        // TODO add your handling code here:
         lbl_ruangan9.setBackground(Color.RED);
          play("key.mp3");
    }//GEN-LAST:event_lbl_ruangan9MouseEntered

    private void lbl_ruangan9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan9MouseExited
        // TODO add your handling code here:
         lbl_ruangan9.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan9MouseExited

    private void lbl_ruangan10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan10MouseClicked
        // TODO add your handling code here:
        FrmMenuUtama mu = new FrmMenuUtama();
        FungsiLayout.setToCenter(mu);
        FungsiLayout.setMaximize(mu);
        mu.setVisible(true);
        dispose();

    }//GEN-LAST:event_lbl_ruangan10MouseClicked

    private void lbl_ruangan10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan10MouseEntered
        // TODO add your handling code here:
          lbl_ruangan10.setBackground(Color.RED);
           play("key.mp3");
    }//GEN-LAST:event_lbl_ruangan10MouseEntered

    private void lbl_ruangan10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan10MouseExited
        // TODO add your handling code here:
         lbl_ruangan10.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan10MouseExited

    private void lbl_ruangan11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan11MouseClicked
        // TODO add your handling code here:
        lbl_ruang.setText("R412");
        panggilRuang();

    }//GEN-LAST:event_lbl_ruangan11MouseClicked

    private void lbl_ruangan11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan11MouseEntered
        // TODO add your handling code here:
          lbl_ruangan11.setBackground(Color.RED);
           play("key.mp3");
    }//GEN-LAST:event_lbl_ruangan11MouseEntered

    private void lbl_ruangan11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan11MouseExited
        // TODO add your handling code here:
         lbl_ruangan11.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan11MouseExited

    private void lbl_ruangan12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan12MouseClicked
        // TODO add your handling code here:
        lbl_ruang.setText("R411");
        panggilRuang();
       
    }//GEN-LAST:event_lbl_ruangan12MouseClicked

    private void lbl_ruangan12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan12MouseEntered
        // TODO add your handling code here:
         lbl_ruangan12.setBackground(Color.RED);
          play("key.mp3");
    }//GEN-LAST:event_lbl_ruangan12MouseEntered

    private void lbl_ruangan12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ruangan12MouseExited
        // TODO add your handling code here:
         lbl_ruangan12.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_lbl_ruangan12MouseExited

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel2KeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

    String message = "Apakah anda yakin ingin keluar ?";
    String title = "Peringatan";
    // display the JOptionPane showConfirmDialog
    int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
    if (reply == JOptionPane.YES_OPTION)
    {
      System.exit(0);
    }
      
    }//GEN-LAST:event_jLabel2MouseClicked
public void panggilRuang()
{
  String ruang,jam,hari,tgl;


        try{
    stmt = con.createStatement();
    rs = stmt.executeQuery("SELECT ruangan_kode FROM tbl_jadwal WHERE ruangan_kode = '"+lbl_ruang.getText()+"' AND hari='"+lbl_hari.getText()+"' and '"+lbl_jam.getText()+"' BETWEEN jam_masuk AND jam_keluar");

    rs.first();
    String nama = rs.getString("ruangan_kode");
    System.out.print(nama);

    if (nama.equals(""))
    {
        JOptionPane.showMessageDialog(null, "Kelas Kosong hihihii");
    }
    else
    {
    System.out.println("isi");
    ruang = lbl_ruang.getText();
        jam = lbl_jam.getText();
        hari = lbl_hari.getText();
        tgl = lbl_tanggal.getText();
        FrmAbsensi1 absen = new FrmAbsensi1(ruang,jam,hari,tgl);
        FungsiLayout.setToCenter(absen);
        FungsiLayout.setMaximize(absen);
        absen.setVisible(true);
        dispose();

    }

    }
    catch(SQLException se)
                {
                     play("2.mp3"); 
                    JOptionPane.showMessageDialog(null, "Kelas Kosong");
                    
                }
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuRuang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_hari;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_pangilRuang;
    private javax.swing.JLabel lbl_ruang;
    private javax.swing.JLabel lbl_ruangan1;
    private javax.swing.JLabel lbl_ruangan10;
    private javax.swing.JLabel lbl_ruangan11;
    private javax.swing.JLabel lbl_ruangan12;
    private javax.swing.JLabel lbl_ruangan2;
    private javax.swing.JLabel lbl_ruangan3;
    private javax.swing.JLabel lbl_ruangan4;
    private javax.swing.JLabel lbl_ruangan5;
    private javax.swing.JLabel lbl_ruangan6;
    private javax.swing.JLabel lbl_ruangan7;
    private javax.swing.JLabel lbl_ruangan8;
    private javax.swing.JLabel lbl_ruangan9;
    private javax.swing.JLabel lbl_tanggal;
    // End of variables declaration//GEN-END:variables
private static String filename;
private static Player player;

public static void play(String musik) {



    try {
            FileInputStream fis     = new FileInputStream("src/"+musik);
            BufferedInputStream bis = new BufferedInputStream(fis);
            player = new Player(bis);
        }
        catch (Exception e) {
            System.out.println("Problem playing file " + filename);
            System.out.println(e);
        }

        // run in new thread to play in background
        new Thread() {
            @Override
            public void run() {
                try {
                    player.play();
                }
                catch (Exception e) { System.out.println(e); }
            }
        }.start();

    }

    public void close()
       {
           player.close();
       }
}
